### PR TITLE
Add protov6 provider with acceptance tests, bump SDK and plugin-go/mux versions

### PR DESCRIPTION
**Pull request by kmoe**
Also bump versions of SDK and mux, and add a procotol v6 provider, not muxed in with the others until mux supports v6.

Acc tests use `TestCase.ProtoV6ProviderFactories` added to the SDK in https://github.com/hashicorp/terraform-plugin-sdk/pull/761.

### CODE REVIEW

**Comment by paddycarver** [comment]
Hmm. Is this related to hashicorp/terraform#28741 only being merged 6 days ago, meaning it would only (I think?) be found in v0.15.4... I'm seeing the code for protocol negotiation in tests on v0.15.4 and not on v0.15.3, so that may be why?

Does this work if we require Terraform v0.15.4 or higher for tests for it?

**Comment by paddycarver** [comment]
Looks like we've got some merge conflicts.

**Comment by kmoe** [comment]
Resolved

**Review by paddycarver — APPROVED** [review]
LGTM. 🚀

**Pull request merged**
