### PR TITLE
Add tests for state preserving plan modifier.

### PR DESCRIPTION
**Pull request by paddycarver**
Update the framework to use hashicorp/terraform-plugin-framework#204.

Add "language" as a property of user, simulating an optional+computed
value with a default.

Add "date_joined" as a property of user, simulating a write-once
computed-only value.

Update framework user tests to check actual values (which we can do,
because they're known) instead of using unnecessary regular expressions.

Check all the attributes in state for our framework user tests.

Add framework user test that language can optionally be set.

Add framework user test that language can be interpolated successfully
even with the PreserveState modifier on it.

### CODE REVIEW

**Review by bflad — APPROVED** [review]
Looks good to me 🚀

**Comment by paddycarver** [comment]
Updated to use `main` and fixed the name of the plan modifier. Still good, @bflad?

**Review by bflad — APPROVED** [review]

**Comment by bflad** [comment]
Ready for rebase, now that terraform-plugin-framework v0.5.0 has been released and pulled in.

**Comment by bflad** [comment]
Going to rebase this branch and pull it in 👍

**Pull request merged**
